version: '3.8'

services:
  app:
    build: .
    image: douyin-live-recorder:local
    environment:
      - TERM=xterm-256color
    tty: true
    stdin_open: true
    shm_size: 1gb
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./backup_config:/app/backup_config
      - ./downloads:/app/downloads
    restart: always
